export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  USER_REGISTRATION_REQUEST: " USER_REGISTRATION_REQUEST",
  USER_REGISTRATION_SUCCESS: " USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: " USER_REGISTRATION_FAILURE",
};
