export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  USER_REGISTRATION_REQUEST: " USER_REGISTRATION_REQUEST",
  USER_REGISTRATION_SUCCESS: " USER_REGISTRATION_SUCCESS",
  USER_REGISTRATION_FAILURE: " USER_REGISTRATION_FAILURE",
};
export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};
export const serviceConstants = {
  GET_ALL_SERVICE_REQUEST: "GET_ALL_SERVICE_REQUEST",
  GET_ALL_SERVICE_SUCCESS: "GET_ALL_SERVICE_SUCCESS",
  GET_ALL_SERVICE_FAILURE: "GET_ALL_SERVICE_FAILURE",
};
export const productConstants = {
  GET_PRODUCTS_BY_SERVICE: " GET_PRODUCTS_BY_SERVICE",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  // GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};
